import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Genesis Swap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://kit.fontawesome.com/9b9304f5bd.js"
        crossorigin="anonymous"
      ></Script>
    </div>
  );
}
